version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  app:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todolist
      MYSQL_PORT: 3306
